### ISSUE TITLE
Verifying Unit Conversions + Coefficients

### ISSUE THREAD

**Issue by nopara73** [ajsteele/bioage#1]
I've been going through the calculations and trying to verify your numbers. In this issue I am sharing my findings.

# Coefficients

They match the paper: https://pmc.ncbi.nlm.nih.gov/articles/PMC5940111/pdf/aging-10-101414.pdf

# Unit Conversions
## Verified:
- [x] Ablumin
- [x] Creatinine
- [x] Glucose
- [x] MCV
- [x] WBC
- [x] RCDW
- [x] Alkaline Phosphatase

### CRP

It seems you are using a molar mass of 105,000 g/mol for C-Reactive Protein (CRP), which would give 95.2381 nmol/L for 1 mg/dL. However, most sources reference a molar mass closer to 115,000 g/mol for CRP, leading to a conversion of 86.96 nmol/L.

This 115,000 g/mol figure is widely used (e.g., [Wikipedia](https://en.wikipedia.org/wiki/C-reactive_protein)) and considers CRP’s pentameric structure. You might want to double-check if this higher molar mass could apply here, as it may bring your result in line with common references.

### Lymphocytes

Probably no issue here, just a minor complication that probably needs not be addressed. It seems you’re using 1% lymphocytes = 1,000 cells/μL (or 1 x 10⁹ cells/L), which is correct if you’re assuming a standard WBC count. This approach works well for estimation, but double-checking against the actual WBC count could ensure accuracy if available.

**Comment by nopara73** [comment]
Oh just noticed you already have a comment on Lymphocytes

`// If not expressed as a percentage, the lymphocyte units here might need changing to get them into the same units as the WBC above`
- [x] Lymphocytes

**Comment by ajsteele** [comment]
Thanks for checking this!

I’m not sure where I got my CRP number from—in fact, one of the improvements I forgot to note in the readme is that I’d like to put the unit conversions in a CSV file which would allow there to be an extra column for the source. Have you found an authoritative source on your travels?

And yes, the lymphocytes conversion should work for now (see later in the code where, if it’s not given in %, it divides the number by the total lymphocyte count), the comment refers to the fact that if a lab reported these in units that weren’t numerically equivalent (I’ve not seen this, and no such units are available in the calculator) that line later in the code would also need to put the WBCs and lymphocyte concentration into the same units before calculating the percentage.

Hope that helps and we should definitely change the CRP conversion if it’s wrong!

**Comment by nopara73** [comment]
Anyhow for pheno age calculation the error is well tolerated using 115,000 g/mol or 105,000 g/mol and CRP or hs-CRP, so at this point I'm just bikeshedding and I'm not bother you further with this issue :)

**Comment by ajsteele** [comment]
Let me know if you find out the conversion factor! I’ve noticed that assigning a single molar mass for conversion can be quite complicated in other tests too, and I’m also not a lab test expert—hopefully at some point I or someone else will have time to chase this up. :)

Thanks pointing this out though!

**Comment by nopara73** [comment]
Sure, btw since we're at it, I have a small longevity podcast. Would you like have a conversation framed as a code review for your pheno age js? Hit me up with [an email](adam.ficsor73@gmail.com) if it interests you!

https://www.youtube.com/playlist?list=PL4nqc85w185sO4i7eR3oUO_lMmlJ2K1cL
